name: Main Branch Pipeline

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-test-deploy-dev:
    name: Main branch pipeline
    runs-on: ubuntu-latest
    concurrency: dev
    environment: dev
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      OKTA_ISSUER: ${{ vars.OKTA_ISSUER }}
      PULUMI_SECRETS_PROVIDER: passphrase
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      WEBINY_PULUMI_BACKEND: s3://wby-dev-webiny-pulumi-state
      WEBINY_OIDC_Role: arn:aws:iam::477761241525:role/service/webiny/dev-webiny-config-WebinyOIDCRole-I9veTmRfbkGT
      WCP_PROJECT_ENVIRONMENT_API_KEY: ${{ secrets.WCP_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ env.WEBINY_OIDC_Role }}
          role-session-name: AscoWebinyDevPipeline

      - name: Install dependencies
        run: yarn --immutable

      - name: Check code formatting
        run: yarn prettier:check

      - name: ESLint
        run: yarn eslint

      - name: Build custom packages
        run: yarn webiny workspaces run build --folder packages

      - name: Run unit tests
        run: yarn test:unit

      - name: Deploy
        run: yarn webiny deploy --env=dev

      - name: Environment summary
        run: yarn webiny info --env=dev >> $GITHUB_STEP_SUMMARY

      - name: Run integration tests
        run: yarn test:integration

      - name: Run end-to-end tests
        run: yarn test:e2e
